kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80          # Request comes at port 8080 on the service infrastructure, gets forwarded to container port 80; see in Deployment.yml, line 20, port 80 is exposed    
      nodePort: 31200
  selector:
    app: mrdevops                    
  type: LoadBalancer    